name: ogg_opus_player_example
description: Demonstrates how to use the ogg_opus_player plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  audio_session: ^0.2.0
  flutter:
    sdk: flutter
  ogg_record_player:
    path: ../
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - audios/test.ogg
