name: ogg_opus_player_example
description: Demonstrates how to use the ogg_opus_player plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ogg_record_player:
    path: ../
  path: ^1.9.0
  path_provider: ^2.1.3
  platform: ^3.1.4
  share_plus: ^9.0.0
  audio_session: ^0.1.19

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - audios/test.ogg
