name: ogg_opus_player_example
description: Demonstrates how to use the ogg_opus_player plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ogg_opus_player:
    path: ../
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  platform: ^3.1.4
  share_plus: ^8.0.2

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - audios/test.ogg
