name: ogg_record_player
description: An ogg opus file player and recorder for flutter.
version: 1.0.1
homepage: https://github.com/SunnatilloShavkatov/ogg_opus_player.git

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  system_clock: ^2.0.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftOggOpusPlayerPlugin
      android:
        package: one.mixin.oggOpusPlayer
        pluginClass: OggOpusPlayerPlugin
