name: ogg_record_player
description: An ogg opus file player and recorder for flutter.
version: 1.0.4
homepage: https://github.com/SunnatilloShavkatov/ogg_record_player

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  system_clock: ^2.0.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftOggOpusPlayerPlugin
      android:
        package: one.mixin.oggOpusPlayer
        pluginClass: OggOpusPlayerPlugin
